package com.baitent.habit_compose.common

object AppStrings {
    const val nameError = "Name cannot be empty"
    const val namePlaceholder = "Name"
    const val appName = "habit_compose"
    const val seeAll = "See All"
    const val todayHabit = "Today Habit"
    const val habitItemText = "İngilizce Çalış"
    const val signUp = "Sign Up"
    const val signIn = "Sign In"
    const val email = "Email"
    const val password = "Password"
    const val passwordPlaceholder = "********"
    const val forgotPassword = "Forgot Password"
    const val passwordConfirmation = "Pasword Confirmation"
    const val passwordConfirmationError = "Passwords do not match"
    const val passwordError = "Password must be at least 6 characters"
    const val emailError = "Please enter a valid email address"
    const val emailEmpty = "Email cannot be empty"
    const val passwordEmpty = "Password cannot be empty"
    const val passwordConfirmationEmpty = "Password Confirmation cannot be empty"
    const val signUpError = "Sign Up Error"
    const val signInError = "Sign In Error"
    const val signUpSuccess = "Sign Up Success"
    const val signInSuccess = "Sign In Success"
    const val signOutSuccess = "Sign Out Success"
    const val signOutError = "Sign Out Error"
    const val signOut = "Sign Out"
    const val signOutConfirmation = "Are you sure you want to sign out?"
    const val yes = "Yes"
    const val no = "No"
    const val rememberMe = "Remember Me"
    const val orLoginWith = "or sign in with"
    const val orSignUpWith = "or sign up with"
    const val welcome = "Welcome to Habit"
    const val welcomeDescription = "Let us help you to track your habit activity!"
    const val name = "Name"
    const val nameEmpty = "Name cannot be empty"
    const val emailPlaceholder = "example@example.com"
}
